### ISSUE TITLE
Clean up code to Standards using consolidation of WP and PHP PSR standards

### ISSUE THREAD

**Issue by kyle-jennings** [kyle-jennings/benjamin#23]
@miklb brought up the importance of using the WP Coding standards, which in turn forced me to look at my code in horror and realize that I need to clean things up.

I don't really like the WP coding standards (gross for example, are Yoda conditions ), and would prefer to use the PHP PSR standards.  We can use phpcs.ruleset.xml to override WP Coding Standards we don't like.  Lets use this issue to determine what we do and dont like.

**Comment by kyle-jennings** [comment]
From WordPress, I do not like:

- Yoda conditions
- using real tabs instead of spaces for indentation
- spaces should used after a bang (ie. ! $is_true)
- spaces around variables when used as an index to an array (ie. $arr[ $index ])
- class method brackets need to be on the same line as the function statement

I'm up in the air about:

- using capitalized snake case names for class names (WordPress uses that for its classes, but PSR wants StudlyCaseNames... using both together can look gross and we cant exactly change WordPress's built in class names)
- using the prefix of 'class-' for the file names of file containing class definitions.  On the one hand, this prevents autoloading from working in according with PSR-4, on the other hand I dont know if the PSR-4 autoloading standards are backwards compatible with php 5.2 which WordPress.org requires)
- extract() - I'm using it for some specific functions where I know exactly what is provided but perhaps its time to not be lazy.

**Comment by miklb** [comment]
Might be easier to skip the WP ruleset and create a custom file.

https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PSR2/ruleset.xml

https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml

Even if just the default psr2 rules, anyone using CodeSniffer should pick up that file to override any default rules they are using. Then you can add rules as you see fit.

Conversely, it's pretty easy to remove the WP rules you don't like, i.e. `<exclude name="WordPress.VIP.AdminBarRemoval.RemovalDetected" />`

**Comment by kyle-jennings** [comment]
@miklb I've decided just to go with the PSR standards.  I'm slowly going through each file and formatting things as I add features and fix bugs.

**Comment by miklb** [comment]
Awesome. I'm about to revisit the project I've been working using your tools, so will see what/where I can contribute. Thanks for addressing this.

**Comment by miklb** [comment]
would this default ruleset work for you along with an `.editorconfig` to normalize tabs & space?

**Comment by miklb** [comment]
I see latest commit addresses this with a `phpcs.ruleset.xml` file. thanks 🎉

**Comment by kyle-jennings** [comment]
Finally getting around to this.  After reflecting, I decided to use the WordPress code standards and have updated the phpcs ruleset to use the which include Core, Docs, and Extra as documented here:  https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

@miklb checkout this branch:  https://github.com/kyle-jennings/benjamin/tree/wpcs

I need to double and triple check everything but I'm hoping to merge that into dev and master soon
