### ISSUE TITLE
Menu Disappears on Smarthones when Navbar sticky Enabled

### ISSUE THREAD

**Issue by joshdelarosa1** [kyle-jennings/benjamin#3]
On smartphones, the menu displays. However, when I tried to click on the menu, it disappears and does not take me to the page. This was replicated on Iphone + Safari & Pixel + Chrome when Navbar sticky on scroll= Yes. When Navbar sticky on scroll= No, the menu functions as it should.

This on WordPress 4.9-alpha-41234 running Benjamin theme.

**Comment by kyle-jennings** [comment]
fixed:

https://github.com/kyle-jennings/benjamin/pull/13/commits/52633299b89e52a9953ec1d754207bb7243552f9#diff-1c1ae65fe9828eb6d3cee4edacf90018R18
