### ISSUE TITLE
Navbar Brand Type not Visable when Menu is Long

### ISSUE THREAD

**Issue by joshdelarosa1** [kyle-jennings/benjamin#4]
Depending on the number of characters in the menu, parts of the Navbar Brand Type is not visible. This is true for Logos or longer text (e.g. more than 10 characters).

As a work around I've had to reduce the number of characters in the menu by shortening the page names.

But if the menu is too short, the logo is not visible as well.

**Comment by kyle-jennings** [comment]
fixed in merge c6aaaf:
https://github.com/kyle-jennings/benjamin/commit/c6aaaf04cddfac71e382ad00d566d05a8a5da6ff
